############################################
# ğŸŒ Hugo Site Settings
############################################

baseURL = "https://pablo.spa/"
languageCode = "en-us"
title = "Pablo Spada"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

############################################
# ğŸ¨ PaperMod Theme Parameters
############################################

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  showBreadCrumbs = true
  showToc = true
  tocOpen = false
  ShowShareButtons = false                     # âŒ Turn off share buttons
  mainSections = ["posts"]
  favicon = "favicon.png"


############################################
# ğŸŒ Multilingual Configuration
############################################

[languages]

  [languages.es]
    languageName = "EspaÃ±ol"
    contentDir = "content/es"
    title = "Pablo Spada"
    weight = 1

  [languages.es.params.homeInfoParams]
    Title = "Hola, Bienvenido"
    Content = "Este es mi blog personal. AquÃ­ comparto ideas y reflexiones. Puedes cambiar de idioma arriba."

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    title = "Pablo Spada"
    weight = 2
    
  [languages.en.params.homeInfoParams]
    Title = "Hi, Welcome!"
    Content = "This is my personal blog where I share thoughts and reflections. You can switch languages above."

############################################
# ğŸ“‚ Menu Configuration
############################################

[menu]

  [[menu.main]]
    identifier = "es"
    name = "ğŸ‡²ğŸ‡½ Es"
    url = "https://pablo.spa/es/"
    weight = 90

  [[menu.main]]
    identifier = "en"
    name = "ğŸ‡¬ğŸ‡§ En"
    url = "https://pablo.spa/en/"
    weight = 91

  [[menu.main]]
  identifier = "admin"
  name = "ğŸ›  Login"
  url = "https://pablo.spa/admin"
  weight = 92
  relURL = false
